### PR TITLE
add LZO to modules

### PR DESCRIPTION
**Pull request by sritchie**
To see if tests pass.

### CODE REVIEW

**Comment by philippwinkler** [comment]
The unit test passes locally. Maybe the lzo2 lib isn't installed on the test machine (which wouldn't surprise me).

**Comment by sritchie** [comment]
Okay, modified to install that dependency as per twitter-lzo's travis definition.

**Comment by philippwinkler** [comment]
Great idea, pulling from twitter. Via [Elephant-Bird](https://github.com/twitter/elephant-bird/blob/master/.travis.yml) we will also need the native gpl compression:

```
before_install:
...  
- git clone git://github.com/twitter/hadoop-lzo.git # for native libgplcompression
  - cd hadoop-lzo
  - git checkout master
  - mvn compile
  - mv target/native/Linux-* ../hadoop-lzo-native
  - cd ..
```
and add the library `$PWD/hadoop-lzo-native/lib` to the environment.

**Comment by sritchie** [comment]
@philippwinkler trying again with a bunch more options :)

**Comment by sritchie** [comment]
Boom, works!

**Pull request merged**
