### PR TITLE
Remove Cascading platform from the base logic

### PR DESCRIPTION
**Pull request by bhiles**
To allow additional platforms to be added to Cascalog, we must first extract the Cascading platform from the base logic.  This pull request begins the attempt to do that.  Additionally, it begins adding in a Clojure platform, but that is barely built.

## How to use

To set the platform you need to use the **with-context** macro and specify which platform to use.

#### Cascading 

    (require '[cascalog.api :as api]		 
        '[cascalog.logic.platform :as platform]
        '[cascalog.cascading.platform])
    (import 'cascalog.cascading.platform.CascadingPlatform)

    (let [nums [[1][2]]]
        (platform/with-context (CascadingPlatform.)
            (api/??<- [?n] (nums ?n))))
    => ([1] [2])

### Clojure

    (require '[cascalog.clojure.platform])
    (import 'cascalog.clojure.platform.ClojurePlatform)

    (let [nums [[1][2]]]
        (platform/with-context (ClojurePlatform.)
            (api/??<- [?n] (nums ?n))))
    => ([(1)] [(2)])

## Steps taken so far

* removed all cascading dependencies from the logic namespace (except for testing.clj)
* pulled in some functions from the cascading namespace into the logic.platform.clj since they appear platform agnostic (like compile-query)
* extended IPlatform to handle to-generator so we only need one dynamic var (*context*) and not two (*context* and *runner)
* built my really simple clojure platform and gave it a new namespace
* modified some tests so they continue using the Cascading platform.  But many tests (about 21) currently fail and I will fix them once I'm more confident the direction I'm moving is the right one.     

## Questions

* Is this approach moving in the right direction?
* Is with-context a good way to handle specifying which platform to use?
* Is creating EmptyPlatform a suitable solution to giving a dynamic var a default value without pulling in an implementation namespace?

### CODE REVIEW

**Comment by sritchie** [comment]
@bhiles , how about next week? I thought the holidays would be less busy, but of course I was wrong.

If you can fix this merge conflict, I'll merge this. Nice work!!

**Comment by sritchie** [comment]
@bhiles just wanted to ping and let you know that I'm good to merge this once the merge conflicts are fixed. Cheers!

**Comment by bhiles** [comment]
@sritchie I'm free almost anytime Wednesday - Sunday this week.

**Comment by bhiles** [comment]
@sritchie the merge conflicts are resolved!!!! :D

**Comment by sritchie** [comment]
Niiiiiice. @sorenmacbeth, you pysched?

**Comment by sritchie** [comment]
@bhiles I did find one issue with this. The cascading platform maps "collectify" across sources, so

`[1 2 3]` and `[[1] [2] [3]]` are equivalent and valid sources. Can we make this change for the in memory?

**Comment by patrickwmcgee** [comment]
:fireworks: Awesome job! :fireworks:

**Comment by bhiles** [comment]
@sritchie yay!  First bug found! I created #266 to address the collectify issue.

**Comment by bhiles** [comment]
@patrickwmcgee thanks!

**Pull request merged**
