### PR TITLE
bump hadoop version

### PR DESCRIPTION
**Pull request by jiacai2050**

### CODE REVIEW

**Comment by jiacai2050** [comment]
<details>
 <summary>Never mind, problem solved.</summary>

Hi @sritchie,
travis always says
```
Could not find artifact org.apache.hadoop:hadoop-client:jar:2.6.0
 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.apache.hadoop:hadoop-client:jar:2.6.0
 in clojars (https://repo.clojars.org/)
Could not find artifact org.apache.hadoop:hadoop-client:jar:2.6.0
 in conjars (https://conjars.org/repo/)
```
 but I can find at
- https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/2.6.0/

Any ideas?
</details>

**Comment by jiacai2050** [comment]
@sritchie  PTAL

**Comment by jiacai2050** [comment]
@sritchie ping

**Comment by sritchie** [comment]
I'd recommend doing this in a fork!

**Comment by jiacai2050** [comment]
Thanks, maybe you can add a notice in README.

**Comment by sritchie** [comment]
I am totally out of touch with the current Hadoop ecosystem, but I loved this project and I am happy to hear at least the implication that it's still useful!

**Pull request closed without merging**
